In [1]:
import pandas as pd
import numpy as np
from urllib.parse import urlparse, urlunparse
import aiohttp
import asyncio
import bs4
import random

MAX_TRACES_PER_USER = 5
DESIRED_TRACES = 1000
OUTPUT_FOLDER = "output"


def get_headers(domain):
    headers = {
        "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:140.0) Gecko/20100101 Firefox/140.0",
    }
    if "facebook" in domain:
        # Facebook returns 400 error when we fake our User-Agent
        headers = None
    return headers

In [2]:
data = pd.read_csv(
    "web_routineness_data/browsing.csv",
    dtype={"id": int, "web_visits_id": int},
    parse_dates=["used_at"],
).drop(columns=["id"])
data.head()

,web_visits_id,panelist_id,url,used_at,active_seconds,domain,subdomain
0,111761051,1421,0,2018-10-05 22:02:38,4,ebesucher.de,NaN
1,111761051,1421,0,2018-10-05 21:41:22,10,ebesucher.de,NaN
2,111761051,1421,0,2018-10-05 21:45:36,5,ebesucher.de,NaN
3,111761051,1421,0,2018-10-05 21:42:22,181,ebesucher.de,NaN
4,111761055,1421,1,2018-10-05 21:47:57,2,klamm.de,NaN

In [3]:
# Sanity check: only keep panelists with a good number of web page visits
REQUIRED_DATAPOINTS = 200

panelists_to_filter = data.groupby("panelist_id").filter(
    lambda x: len(x) < REQUIRED_DATAPOINTS
)["panelist_id"].unique()

print(f"Filtering out {len(panelists_to_filter)} panelists with less than {REQUIRED_DATAPOINTS} datapoints")

data_filtered = data[~data["panelist_id"].isin(panelists_to_filter)].copy()
print("Rows:", len(data_filtered))
data_filtered.sort_values("used_at").iloc[np.r_[0:5, -5:0]]

Filtering out 319 panelists with less than 200 datapoints
Rows: 9127431

,web_visits_id,panelist_id,url,used_at,active_seconds,domain,subdomain
1369019,114016772,1849,498963,2018-10-01 00:00:00,8,nicequest.com,NaN
1315961,113973380,750,481401,2018-10-01 00:00:00,2,vasilisaroom.site,NaN
1232915,113894036,957,454324,2018-10-01 00:00:00,6,google.com,NaN
1520755,114158144,1982,552480,2018-10-01 00:00:00,2,facebook.com,NaN
1346500,113996676,1170,491134,2018-10-01 00:00:01,5,ebay-kleinanzeigen.de,NaN
8884856,124428860,1627,2918269,2018-10-31 23:59:58,16,ebay.de,NaN
8944905,124539076,1067,241123,2018-10-31 23:59:58,10,gfk.de,ecpo.
9091905,124804680,1226,813332,2018-10-31 23:59:58,452,mypersonalroutine.com,de.
8938760,124531492,177,2934742,2018-10-31 23:59:59,6,crazyslip.com,NaN
8984063,124604448,248,10894,2018-10-31 23:59:59,4,wish.com,NaN

In [4]:
# split data into 30 min buckets
BUCKET_SIZE = 30 * 60

start_time = data_filtered['used_at'].min()
buckets = data_filtered["used_at"].sub(start_time)
data_filtered['bucket'] = (buckets.dt.total_seconds() // BUCKET_SIZE).astype(int)
print("Rows:", len(data_filtered))
data_filtered.sort_values("used_at").iloc[np.r_[0:5, -5:0]]

Rows: 9127431

,web_visits_id,panelist_id,url,used_at,active_seconds,domain,subdomain,bucket
1369019,114016772,1849,498963,2018-10-01 00:00:00,8,nicequest.com,NaN,0
1315961,113973380,750,481401,2018-10-01 00:00:00,2,vasilisaroom.site,NaN,0
1232915,113894036,957,454324,2018-10-01 00:00:00,6,google.com,NaN,0
1520755,114158144,1982,552480,2018-10-01 00:00:00,2,facebook.com,NaN,0
1346500,113996676,1170,491134,2018-10-01 00:00:01,5,ebay-kleinanzeigen.de,NaN,0
8884856,124428860,1627,2918269,2018-10-31 23:59:58,16,ebay.de,NaN,1487
8944905,124539076,1067,241123,2018-10-31 23:59:58,10,gfk.de,ecpo.,1487
9091905,124804680,1226,813332,2018-10-31 23:59:58,452,mypersonalroutine.com,de.,1487
8938760,124531492,177,2934742,2018-10-31 23:59:59,6,crazyslip.com,NaN,1487
8984063,124604448,248,10894,2018-10-31 23:59:59,4,wish.com,NaN,1487

In [5]:
# Filter out buckets whose size is outside the 35th-85th percentiles range
LOWER_BOUND = 0.35
UPPER_BOUND = 0.85

bucket_sizes = data_filtered.groupby(["panelist_id", "bucket"]).size()
lower_bound = bucket_sizes.quantile(LOWER_BOUND)
upper_bound = bucket_sizes.quantile(UPPER_BOUND)
print(f"Lower bound: {lower_bound}, Upper bound: {upper_bound}")

data_good_buckets = data_filtered.groupby(["panelist_id", "bucket"]).filter(
    lambda x: lower_bound <= len(x) <= upper_bound
)
print("Rows:", len(data_good_buckets))
data_good_buckets.iloc[np.r_[0:5, -5:0]]

Lower bound: 8.0, Upper bound: 47.0
Rows: 4069727

,web_visits_id,panelist_id,url,used_at,active_seconds,domain,subdomain,bucket
1,111761051,1421,0,2018-10-05 21:41:22,10,ebesucher.de,NaN,235
2,111761051,1421,0,2018-10-05 21:45:36,5,ebesucher.de,NaN,235
3,111761051,1421,0,2018-10-05 21:42:22,181,ebesucher.de,NaN,235
4,111761055,1421,1,2018-10-05 21:47:57,2,klamm.de,NaN,235
5,111761055,1421,2,2018-10-05 21:47:40,1,klamm.de,NaN,235
9151238,124906196,1739,236,2018-10-31 16:52:12,105,facebook.com,NaN,1473
9151239,124906196,1739,236,2018-10-31 16:51:04,8,facebook.com,NaN,1473
9151240,124906200,1739,2997793,2018-10-31 16:50:10,2,goo.gl,NaN,1473
9151241,124906204,1739,2997794,2018-10-31 16:50:12,52,focus.de,NaN,1473
9151242,124906208,1739,2997795,2018-10-31 16:51:12,60,berliner-sonntagsblatt.de,NaN,1473

In [6]:
# Filter out buckets whose web page visits all occur within a 15 minute range
# We want traces to be at least somewhat spread out in time
REQUIRED_TIME_SPAN = 15 * 60

data_good_range = data_good_buckets.groupby(["panelist_id", "bucket"]).filter(
    lambda x: (x["used_at"].max() - x["used_at"].min()).total_seconds() >= REQUIRED_TIME_SPAN
)
print("Rows:", len(data_good_range))
data_good_range.iloc[np.r_[0:5, -5:0]]

Rows: 2673105

,web_visits_id,panelist_id,url,used_at,active_seconds,domain,subdomain,bucket
75,111762035,789,21,2018-10-05 16:53:08,4,amazon.de,NaN,225
82,111762043,789,27,2018-10-05 16:42:14,10,icloud.com,NaN,225
83,111762043,789,28,2018-10-05 16:31:04,2,icloud.com,NaN,225
84,111762043,789,29,2018-10-05 16:53:18,20,icloud.com,NaN,225
85,111762043,789,30,2018-10-05 16:52:49,5,icloud.com,NaN,225
9151238,124906196,1739,236,2018-10-31 16:52:12,105,facebook.com,NaN,1473
9151239,124906196,1739,236,2018-10-31 16:51:04,8,facebook.com,NaN,1473
9151240,124906200,1739,2997793,2018-10-31 16:50:10,2,goo.gl,NaN,1473
9151241,124906204,1739,2997794,2018-10-31 16:50:12,52,focus.de,NaN,1473
9151242,124906208,1739,2997795,2018-10-31 16:51:12,60,berliner-sonntagsblatt.de,NaN,1473

In [7]:
# Keep up to MAX_TRACES_PER_USER buckets per panelist


def filter_buckets(df):
    grouped = df.groupby("bucket")
    if len(grouped) <= MAX_TRACES_PER_USER:
        return df
    else:
        indices = np.arange(grouped.ngroups)
        np.random.shuffle(indices)
        selected_buckets = indices[:MAX_TRACES_PER_USER]
        return df[grouped.ngroup().isin(selected_buckets)]


data_pruned = (
    data_good_range.groupby("panelist_id")
    .apply(filter_buckets, include_groups=False)
    .reset_index()
    .drop(columns=["level_1"])
)
print("Rows:", len(data_pruned))
data_pruned.iloc[np.r_[0:5, -5:0]]

Rows: 215340

,panelist_id,web_visits_id,url,used_at,active_seconds,domain,subdomain,bucket
0,0,112304243,791,2018-10-06 20:47:11,2,youtube.com,NaN,281
1,0,112304243,214,2018-10-06 20:58:31,72,youtube.com,NaN,281
2,0,112304243,791,2018-10-06 20:51:11,4,youtube.com,NaN,281
3,0,112304243,114934,2018-10-06 20:35:50,42,youtube.com,NaN,281
4,0,112304243,114936,2018-10-06 20:51:15,179,youtube.com,NaN,281
215335,2147,118683568,113792,2018-10-15 21:16:57,24,sfgame.de,s4.,714
215336,2147,118683572,1317017,2018-10-15 21:13:50,71,youtube.com,NaN,714
215337,2147,118683572,1903075,2018-10-15 21:05:23,152,youtube.com,NaN,714
215338,2147,118683572,1317017,2018-10-15 21:07:55,187,youtube.com,NaN,714
215339,2147,118683576,78859,2018-10-15 21:17:23,6,adobe.com,get.,714

In [18]:
# Combine subdomain and domain into a single column
data_transformed = data_pruned.copy()
data_transformed["subdomain"] = data_transformed["subdomain"].fillna("")
data_transformed["domain"] = data_transformed["subdomain"] + data_transformed["domain"]
data_transformed.drop(columns=["subdomain"], inplace=True)
data_transformed.iloc[np.r_[0:5, -5:0]]

,panelist_id,web_visits_id,url,used_at,active_seconds,domain,bucket
0,0,112304243,791,2018-10-06 20:47:11,2,youtube.com,281
1,0,112304243,214,2018-10-06 20:58:31,72,youtube.com,281
2,0,112304243,791,2018-10-06 20:51:11,4,youtube.com,281
3,0,112304243,114934,2018-10-06 20:35:50,42,youtube.com,281
4,0,112304243,114936,2018-10-06 20:51:15,179,youtube.com,281
215335,2147,118683568,113792,2018-10-15 21:16:57,24,s4.sfgame.de,714
215336,2147,118683572,1317017,2018-10-15 21:13:50,71,youtube.com,714
215337,2147,118683572,1903075,2018-10-15 21:05:23,152,youtube.com,714
215338,2147,118683572,1317017,2018-10-15 21:07:55,187,youtube.com,714
215339,2147,118683576,78859,2018-10-15 21:17:23,6,get.adobe.com,714

In [ ]:
remap = {}


def simplify_domain(domain):
    # some domains include a subdomain that don't response to GET requests
    # we should retry them with their main domain
    parts = domain.strip(".").split(".")
    if len(parts) > 2:
        return ".".join(parts[-2:])
    return None


async def build_mapping(domain, session):
    if domain not in remap:
        # prevent concurrent calls from both building the same mapping
        event = asyncio.Event()
        remap[domain] = event

        try:
            print(f"Fetching mapping for {domain}")
            response = await session.get(f"http://{domain}", headers=get_headers(domain))
            await response.read()
            remap[domain] = response.url
            print(f"Mapping {domain} to {response.url}")
        except Exception as e:
            if str(e):
                print(f"Error fetching {domain}: {e}")
            else:
                print(f"Error fetching {domain}: {repr(e)}")

            simplified = simplify_domain(domain)
            if not simplified:
                print(f"Can't simplify {domain}, setting to None")
                remap[domain] = None
            else:
                await build_mapping(simplified, session)
                remap[domain] = remap[simplified]
                print(f"Simplified mapping {domain} to {remap[domain]}")

        event.set()
    elif isinstance(remap[domain], asyncio.Event):
        # caller expects this function to finish only after the mapping is built
        await remap[domain].wait()


async def build_all_mappings(unique_domains):
    async with aiohttp.ClientSession(
        connector=aiohttp.TCPConnector(
            ssl=False,
            keepalive_timeout=2,
            limit=150,
        ),
        raise_for_status=True,
        auto_decompress=False,
        timeout=aiohttp.ClientTimeout(total=None, sock_connect=10, sock_read=10),
    ) as session:
        await asyncio.gather(*(build_mapping(domain, session) for domain in unique_domains))
    return remap

In [20]:
data_remapped = data_transformed.copy()
unique_domains = data_transformed["domain"].unique()
mapping = await build_all_mappings(unique_domains)
data_remapped["domain"] = data_remapped["domain"].map(mapping)

Fetching mapping for youtube.com
Fetching mapping for myanimelist.net
Fetching mapping for google.de
Fetching mapping for warensendung.org
Fetching mapping for amazon.de
Fetching mapping for ofr.ebay.de
Fetching mapping for signin.ebay.de
Fetching mapping for offer.ebay.de
Fetching mapping for invoice.ebay.de
Fetching mapping for my.ebay.de
Fetching mapping for ebay.de
Fetching mapping for k2b-bulk.ebay.de
Fetching mapping for k2b-print.ebay.de
Fetching mapping for postage.ebay.de
Fetching mapping for res.ebay.de
Fetching mapping for hp.myway.com
Fetching mapping for navigator.gmx.net
Fetching mapping for gmx.net
Fetching mapping for deref-gmx.net
Fetching mapping for refrago.de
Fetching mapping for nachspielzeit-community.de
Fetching mapping for nicequest.com
Fetching mapping for ww2.nicequest.com
Fetching mapping for paypal.com
Fetching mapping for webmail.umwelt-campus.de
Fetching mapping for studienkreis.de
Fetching mapping for spreadshirt.de
Fetching mapping for partner.spreadshirt.de
Fetching mapping for app.plus500.com
Fetching mapping for de.chaturbate.com
Fetching mapping for chaturbate.com
Fetching mapping for xnxx.com
Fetching mapping for umwelt-campus.de
Fetching mapping for qis.hochschule-trier.de
Fetching mapping for netmoms.de
Fetching mapping for bewerbungsschreiben.org
Fetching mapping for startfenster.de
Fetching mapping for sm.de
Fetching mapping for spk-vorpommern.de
Fetching mapping for facebook.com
Fetching mapping for apps.facebook.com
Fetching mapping for otto.de
Fetching mapping for zoo.stralsund.de
Fetching mapping for t-online.de
Fetching mapping for email.t-online.de
Fetching mapping for vapi.intapi.com
Fetching mapping for accounts.login.idm.telekom.com
Fetching mapping for de-de.facebook.com
Fetching mapping for suche.t-online.de
Fetching mapping for pv-magazine.de
Fetching mapping for de.trustpilot.com
Fetching mapping for presseportal.de
Fetching mapping for branchenbuch.kaeuferportal.de
Fetching mapping for energate-messenger.de
Fetching mapping for surveys.irbureau.com
Fetching mapping for mep-werke.de
Fetching mapping for eis.de
Fetching mapping for e-news.eis.de
Fetching mapping for fittkaumaass.com
Fetching mapping for bap.navigator.web.de
Fetching mapping for web.de
Fetching mapping for cashbackdeals.de
Fetching mapping for bild.de
Fetching mapping for moebel-gewinnen.de
Fetching mapping for omnislots.com
Fetching mapping for tipp24.com
Fetching mapping for shop.samsung.com
Fetching mapping for stern.de
Fetching mapping for 3c-bap.web.de
Fetching mapping for games.web.de
Fetching mapping for navigator.web.de
Fetching mapping for 3c.web.de
Fetching mapping for umfrage.i24.cc
Fetching mapping for gala.de
Fetching mapping for vegascasino.com
Fetching mapping for handyservice.de
Fetching mapping for suche.gmx.net
Fetching mapping for psd-nuernberg.de
Fetching mapping for moderne-hausfrau.de
Fetching mapping for www.money
Fetching mapping for moneyfix.de
Fetching mapping for kautionskasse.de
Fetching mapping for dl.gmx.net
Fetching mapping for t.17track.net
Fetching mapping for paintingqueen.de
Fetching mapping for picmondoo.de
Fetching mapping for tvnow.de
Fetching mapping for poco.de
Fetching mapping for hotgaylist.com
Fetching mapping for de.wikipedia.org
Fetching mapping for mvbnet.de
Fetching mapping for aol.de
Fetching mapping for login.aol.com
Fetching mapping for mail.aol.com
Fetching mapping for huffingtonpost.de
Fetching mapping for o2online.de
Fetching mapping for login.o2online.de
Fetching mapping for ing-diba.de
Fetching mapping for banking.ing-diba.de
Fetching mapping for medialitaetentwickeln.net
Fetching mapping for versandapo.de
Fetching mapping for mobile.de
Fetching mapping for suchen.mobile.de
Fetching mapping for meine-news.de
Fetching mapping for zumfahren.de
Fetching mapping for icloud.com
Fetching mapping for kinox.io
Fetching mapping for streamcloud.eu
Fetching mapping for cobalten.com
Fetching mapping for workfromhomejobsonline.co
Fetching mapping for guildofangels.net
Fetching mapping for goldesel.to
Fetching mapping for cdnondemand.org
Fetching mapping for bet365.com
Fetching mapping for kinos.to
Fetching mapping for mail.google.com
Fetching mapping for login.die-kleine-kamera.de
Fetching mapping for mail.yahoo.com
Fetching mapping for google.com
Fetching mapping for sheetmusicdirect.com
Fetching mapping for musicnotes.com
Fetching mapping for letternoteplayer.com
Fetching mapping for tabs.ultimate-guitar.com
Fetching mapping for ultimate-guitar.com
Fetching mapping for results.searchlock.com
Fetching mapping for abendblatt.de
Fetching mapping for pamcdn.avast.com
Fetching mapping for retrotubeclips.com
Fetching mapping for de.xhamster.com
Fetching mapping for tubepornlarge.com
Fetching mapping for vporn.com
Fetching mapping for nastyvideotube.com
Fetching mapping for de.pornhub.com
Fetching mapping for wikipedia.de
Fetching mapping for mozilla.org
Fetching mapping for xxxmom.pro
Fetching mapping for fuckmoral.com
Fetching mapping for nuvid.com
Fetching mapping for txxx.com
Fetching mapping for xxxtubeset.com
Fetching mapping for 18qt.com
Fetching mapping for coffetube.com
Fetching mapping for zdf.de
Fetching mapping for deutschlandcard.de
Fetching mapping for heise.de
Fetching mapping for startseite24.net
Fetching mapping for youporngay.com
Fetching mapping for businessinsider.de
Fetching mapping for immonet.de
Fetching mapping for ardmediathek.de
Fetching mapping for wertpapiere.ing-diba.de
Fetching mapping for tvspielfilm.de
Fetching mapping for macwelt.de
Fetching mapping for dosdude1.com
Fetching mapping for fonepaw.de
Fetching mapping for support.apple.com
Fetching mapping for kunde.comdirect.de
Fetching mapping for videobuster.de
Fetching mapping for filmstarts.de
Fetching mapping for blu-ray-rezensionen.net
Fetching mapping for web.nielsennetpanel.com
Fetching mapping for s.to
Fetching mapping for serienjunkies.de
Fetching mapping for accounts.google.com
Fetching mapping for opera.com
Fetching mapping for outlook.live.com
Fetching mapping for webmail.freenet.de
Fetching mapping for freenet.de
Fetching mapping for gebrauchtcomputer24.de
Fetching mapping for web.gdp-group.com
Fetching mapping for spk-westholstein.de
Fetching mapping for g2a.com
Fetching mapping for bing.com
Fetching mapping for gocdkeys.com
Fetching mapping for g2play.net
Fetching mapping for pay.ebay.de
Fetching mapping for shoop.de
Fetching mapping for twitch.tv
Fetching mapping for share-links.biz
Fetching mapping for update3.jdownloader.org
Fetching mapping for my.jdownloader.org
Fetching mapping for shop.spyoff.com
Fetching mapping for share-online.biz
Fetching mapping for uploaded.net
Fetching mapping for mmogamesworld.com
Fetching mapping for geniusdisplay.com
Fetching mapping for de.redtube.com
Fetching mapping for redtube.com
Fetching mapping for login.webgo.de
Fetching mapping for barmer.de
Fetching mapping for smallpdf.com
Fetching mapping for mail.de
Fetching mapping for my.mail.de
Fetching mapping for markt.de
Fetching mapping for erotik.markt.de
Fetching mapping for cap.attempts.securecode.com
Fetching mapping for queer.de
Fetching mapping for tiervermittlung.de
Fetching mapping for computerbild.de
Fetching mapping for howoge.de
Fetching mapping for breitband.telekom-dienste.de
Fetching mapping for mietershop.telekom-dienste.de
Fetching mapping for telekom.de
Fetching mapping for plus.google.com
Fetching mapping for tumblr.com
Fetching mapping for partnernet.amazon.de
Fetching mapping for adcell.de
Fetching mapping for feedbaxx.de
Fetching mapping for surveys.illuminas.com
Fetching mapping for globalkitchencouncil.de
Fetching mapping for bei-mustermanns.de
Fetching mapping for bulksell.ebay.de
Fetching mapping for yahoo.de
Fetching mapping for meinungsclub.de
Fetching mapping for smartmobil.de
Fetching mapping for edgeapi.innovatemr.net
Fetching mapping for verbaco.de
Fetching mapping for surveys.paradigmsample.com
Fetching mapping for s-dri.com
Fetching mapping for lottoland.com
Fetching mapping for nuechtern-mafo.de
Fetching mapping for meinlogin.email
Fetching mapping for survey.cmix.com
Fetching mapping for hub.m3globalresearch.com
Fetching mapping for surveys.harrisinsights.com
Fetching mapping for brandinvitation.com
Fetching mapping for mein-login.net
Fetching mapping for banking.sparda-west.de
Fetching mapping for sparda-west.de
Fetching mapping for eur04.safelinks.protection.outlook.com
Fetching mapping for nam02.safelinks.protection.outlook.com
Fetching mapping for nam03.safelinks.protection.outlook.com
Fetching mapping for ebay-kleinanzeigen.de
Fetching mapping for googleadservices.com
Fetching mapping for blablacar.de
Fetching mapping for storagetos.datamart.windows.com
Fetching mapping for versand-status.de
Fetching mapping for stage-entertainment.de
Fetching mapping for groupon.de
Fetching mapping for shop.netto-online.de
Fetching mapping for dwdl.de
Fetching mapping for abload.de
Fetching mapping for waz.de
Fetching mapping for lidl-kochzauber.de
Fetching mapping for forum.digitalfernsehen.de
Fetching mapping for kochbox.kochhaus.de
Fetching mapping for ausschreibungen-deutschland.de
Fetching mapping for express.de
Fetching mapping for weltbild.de
Fetching mapping for stream-mydirtyhobby.co
Fetching mapping for oload.icu
Fetching mapping for musik-sammler.de
Fetching mapping for supermarktblog.com
Fetching mapping for moviepilot.de
Fetching mapping for jameda.de
Fetching mapping for betreut.de
Fetching mapping for tipp.kicker.de
Fetching mapping for nolp.dhl.de
Fetching mapping for s.morpace.com
Fetching mapping for plus.de
Fetching mapping for trendfrage.de
Fetching mapping for kunde.trend-research.de
Fetching mapping for conrad.de
Fetching mapping for news.google.com
Fetching mapping for pcgameshardware.de
Fetching mapping for buffed.de
Fetching mapping for gamona.de
Fetching mapping for instagram.com
Fetching mapping for reddit.com
Fetching mapping for onetz.de
Fetching mapping for giga.de
Fetching mapping for de.nametests.com
Fetching mapping for kino.de
Fetching mapping for dorodeutschland.de
Fetching mapping for licht-erlebnisse.de
Fetching mapping for bonusbitcoin.co
Fetching mapping for csgolive.com
Fetching mapping for netflix.com
Fetching mapping for en.wikipedia.org
Fetching mapping for cryptoakademie.com
Fetching mapping for communicator.strato.de
Fetching mapping for web.whatsapp.com
Fetching mapping for csgo.99damage.de
Fetching mapping for steamcommunity.com
Fetching mapping for eu.diablo3.com
Fetching mapping for zalando.de
Fetching mapping for freebitco.in
Fetching mapping for moondash.co.in
Fetching mapping for mellowads.com
Fetching mapping for moondoge.co.in
Fetching mapping for moonliteco.in
Fetching mapping for support.hp.com
Fetching mapping for ps.bahn.de
Fetching mapping for bahn.de
Fetching mapping for shop.flixbus.de
Fetching mapping for flixbus.de
Fetching mapping for unsubscribe.use.cc
Fetching mapping for ecpo.gfk.de
Fetching mapping for mail.vodafone.de
Fetching mapping for meinferrero.ferrero.de
Fetching mapping for survey.hopp-marktforschung.de
Fetching mapping for netto-online.de
Fetching mapping for zeit.de
Fetching mapping for stampinup.com
Fetching mapping for my.stampinup.com
Fetching mapping for su-media.s3.amazonaws.com
Fetching mapping for wundermix.de
Fetching mapping for thecraftspa.blogspot.com
Fetching mapping for wuestenrotdirect.de
Fetching mapping for martinaziehlmitpamperedchef.de
Fetching mapping for martinaziehl.blogspot.com
Fetching mapping for achgut.com
Fetching mapping for efiliale.de
Fetching mapping for shop.deutschepost.de
Fetching mapping for banking.sparda-hessen.de
Fetching mapping for sparda-hessen.de
Fetching mapping for degussa-bank.de
Fetching mapping for banking.degussa-bank.de
Fetching mapping for portal.epost.de
Fetching mapping for epost.de
Fetching mapping for deutschepost.de
Fetching mapping for op-marburg.de
Fetching mapping for mylittlefarmies.upjers.com
Fetching mapping for mylittlefarmies.de
Fetching mapping for rover.ebay.com
Fetching mapping for mail01.toom-baumarkt.de
Fetching mapping for toom.de
Fetching mapping for questler.de
Fetching mapping for hoerzu.de
Fetching mapping for qchefsdental.de
Fetching mapping for gameladen.com
Fetching mapping for de.yahoo.com
Fetching mapping for tagesgeldzinsen.com
Fetching mapping for easycredit.de
Fetching mapping for ecosia.org
Fetching mapping for spieleland.de
Fetching mapping for apple.com
Fetching mapping for sparkasse-meissen.de
Fetching mapping for deka.de
Fetching mapping for login.yahoo.com
Fetching mapping for truefire.com
Fetching mapping for chordu.com
Fetching mapping for vbb.de
Fetching mapping for fahrinfo.vbb.de
Fetching mapping for parship.de
Fetching mapping for liebesdrama.de
Fetching mapping for apollokino.de
Fetching mapping for ndr.de
Fetching mapping for passionmassage.de
Fetching mapping for my.hypovereinsbank.de
Fetching mapping for hypovereinsbank.de
Fetching mapping for touch.kaspersky.com
Fetching mapping for booklooker.de
Fetching mapping for projects.invisionapp.com
Fetching mapping for buecher.de
Fetching mapping for secure.booklooker.de
Fetching mapping for privacy.microsoft.com
Fetching mapping for go.microsoft.com
Fetching mapping for comodo.com
Fetching mapping for support.google.com
Fetching mapping for transparencyreport.google.com
Fetching mapping for themen.ebay-kleinanzeigen.de
Fetching mapping for sparkasse.de
Fetching mapping for sskm.de
Fetching mapping for check24.de
Fetching mapping for getdigital.de
Fetching mapping for gameserver.4players.de
Fetching mapping for login.4players.de
Fetching mapping for minecraft.net
Fetching mapping for myhermes.de
Fetching mapping for gmx.de
Fetching mapping for nintendo.de
Fetching mapping for praxistipps.chip.de
Fetching mapping for en-americas-support.nintendo.com
Fetching mapping for minecraftforum.de
Fetching mapping for gutefrage.net
Fetching mapping for minecraft-server.eu
Fetching mapping for minecraft-de.gamepedia.com
Fetching mapping for tutonaut.de
Fetching mapping for devbix.com
Fetching mapping for minecraftforum.net
Fetching mapping for spieletipps.de
Fetching mapping for imgur.com
Fetching mapping for java.com
Fetching mapping for chip.de
Fetching mapping for bugs.mojang.com
Fetching mapping for ghoulesmetalproducts666.bigcartel.com
Fetching mapping for spiegel.de
Fetching mapping for reduxan.de
Fetching mapping for recording-scheduler.eye-square.com
Fetching mapping for bonus-bunny.de
Fetching mapping for bimago.de
Fetching mapping for surveys.jibunu.com
Fetching mapping for toledo.kuleuven.be
Fetching mapping for idp.kuleuven.be
Fetching mapping for web.telegram.org
Fetching mapping for vtk.be
Fetching mapping for mail.tu-chemnitz.de
Fetching mapping for webwsp.aps.kuleuven.be
Fetching mapping for kuleuven.be
Fetching mapping for tele5.de
Fetching mapping for p.cygnus.cc.kuleuven.be
Fetching mapping for startpage.com
Fetching mapping for abendzeitung-muenchen.de
Fetching mapping for texwelt.de
Fetching mapping for der-farang.com
Fetching mapping for mega.nz
Fetching mapping for dkb.de
Fetching mapping for booking.com
Fetching mapping for agoda.com
Fetching mapping for secure.booking.com
Fetching mapping for nutaku.net
Fetching mapping for cuntwars.com
Fetching mapping for sport1.de
Fetching mapping for maps.google.com
Fetching mapping for google.com.br
Fetching mapping for bibionevillapark.com
Fetching mapping for be.bookingexpert.it
Fetching mapping for fcbayern.com
Fetching mapping for landal.de
Fetching mapping for meinereiseangebote.de
Fetching mapping for tui.com
Fetching mapping for mytoys.de
Fetching mapping for booking.flygermania.com
Fetching mapping for flygermania.com
Fetching mapping for baur.de
Fetching mapping for shop.baru.be
Fetching mapping for baru.be
Fetching mapping for topskwlfilter.de
Fetching mapping for allegro.pl
Fetching mapping for archiwum.allegro.pl
Fetching mapping for vimeo.com
Fetching mapping for bierbasis.de
Fetching mapping for vfv06.de
Fetching mapping for roundcube.hhu.de
Fetching mapping for umfragen.intquest.de
Fetching mapping for mymarktforschung.de
Fetching mapping for surveys.mymarktforschung.de
Fetching mapping for berufskolleg-neuss.de
Fetching mapping for ecdl.de
Fetching mapping for karrierebibel.de
Fetching mapping for expedia.de
Fetching mapping for cint.insightexpressai.com
Fetching mapping for booking.cb.expedia.de
Fetching mapping for b.expedia.de
Fetching mapping for browser-hub.eye-square.com
Fetching mapping for googlemail.com
Fetching mapping for de.mypersonalroutine.com
Fetching mapping for login.live.com
Fetching mapping for onedrive.live.com
Fetching mapping for de.123rf.com
Fetching mapping for eventrakete.de
Fetching mapping for web2.cylex.de
Fetching mapping for tp-link.com
Fetching mapping for static.tp-link.com
Fetching mapping for asbbs.de
Fetching mapping for open.spotify.com
Fetching mapping for download2.medion.com
Fetching mapping for medion.com
Fetching mapping for nielsenonlinerewards.com
Fetching mapping for edeka.de
Fetching mapping for sat1.de
Fetching mapping for ankerkraut.de
Fetching mapping for diesiedleronline.de
Fetching mapping for topeleven.com
Fetching mapping for dso-karten.de
Fetching mapping for outlook.ebz-group.com
Fetching mapping for jackpot.de
Fetching mapping for 7tv.de
Fetching mapping for rezeptschachtel.de
Fetching mapping for tnaflix.com
Fetching mapping for support.conrad.de
Fetching mapping for veranstaltungen.campact.de
Fetching mapping for youporn.com
Fetching mapping for bankofscotland.de
Fetching mapping for banking.bankofscotland.de
Fetching mapping for viebrockhaus.de
Fetching mapping for bauhaus.info
Fetching mapping for jonastone.de
Fetching mapping for optamassivhaus.com
Fetching mapping for wiwo.de
Fetching mapping for board.jdownloader.org
Fetching mapping for synology-forum.de
Fetching mapping for cc-community.net
Fetching mapping for sparkasse-siegen.de
Fetching mapping for github.com
Fetching mapping for laengengrad-breitengrad.de
Fetching mapping for aqicn.org
Fetching mapping for eporner.com
Fetching mapping for hausinfo.ch
Fetching mapping for docs.google.com
Fetching mapping for drive.google.com
Fetching mapping for s21-de.battleknight.gameforge.com
Fetching mapping for aplusainteractif.com
Fetching mapping for panel.se
Fetching mapping for s22-de.battleknight.gameforge.com
Fetching mapping for geek-whisper.de
Fetching mapping for s17-de.battleknight.gameforge.com
Fetching mapping for s19-de.battleknight.gameforge.com
Fetching mapping for s20-de.battleknight.gameforge.com
Fetching mapping for media.socialblue.com
Fetching mapping for tasteofcinema.com
Fetching mapping for petazwei.de
Fetching mapping for reifefrauen.com
Fetching mapping for wwa.flirtygirls.de
Fetching mapping for wow-date.de
Fetching mapping for bumsnet.de
Fetching mapping for royalgames.com
Fetching mapping for nord24.de
Fetching mapping for wort-suchen.de
Fetching mapping for sieh-an.de
Fetching mapping for mesg.ebay.de
Fetching mapping for wcp.daimler.com
Fetching mapping for comdirect.de
Fetching mapping for getadblock.com
Fetching mapping for survey.dubiku.de
Fetching mapping for rv24.de
Fetching mapping for portal.admiraldirekt.de
Fetching mapping for allsecur.de
Fetching mapping for motortests.de
Fetching mapping for targobank.de
Fetching mapping for misterspex.de
Fetching mapping for surveys.system1research.com
Fetching mapping for studon.fau.de
Fetching mapping for momox.de
Fetching mapping for rebuy.de
Fetching mapping for cj.greenfieldonline.com
Fetching mapping for msi-aci.com
Fetching mapping for futbin.com
Fetching mapping for lieferheld.de
Fetching mapping for hqporner.com
Fetching mapping for humblebundle.com
Fetching mapping for diebahn.de
Fetching mapping for reiseauskunft.bahn.de
Fetching mapping for watchwrestling.ac
Fetching mapping for educadegree.com
Fetching mapping for l.facebook.com
Fetching mapping for dirtypornvids.com
Fetching mapping for de.thegay.com
Fetching mapping for boyfriendtv.com
Fetching mapping for tube8.com

In [21]:
print("Rows:", len(data_pruned))
data_remapped.iloc[np.r_[0:5, -5:0]]

Rows: 215340

,panelist_id,web_visits_id,url,used_at,active_seconds,domain,bucket
0,0,112304243,791,2018-10-06 20:47:11,2,https://www.youtube.com/,281
1,0,112304243,214,2018-10-06 20:58:31,72,https://www.youtube.com/,281
2,0,112304243,791,2018-10-06 20:51:11,4,https://www.youtube.com/,281
3,0,112304243,114934,2018-10-06 20:35:50,42,https://www.youtube.com/,281
4,0,112304243,114936,2018-10-06 20:51:15,179,https://www.youtube.com/,281
215335,2147,118683568,113792,2018-10-15 21:16:57,24,https://sfgame.net/,714
215336,2147,118683572,1317017,2018-10-15 21:13:50,71,https://www.youtube.com/,714
215337,2147,118683572,1903075,2018-10-15 21:05:23,152,https://www.youtube.com/,714
215338,2147,118683572,1317017,2018-10-15 21:07:55,187,https://www.youtube.com/,714
215339,2147,118683576,78859,2018-10-15 21:17:23,6,None,714

In [22]:
# Filter out all traces with website visits to invalid URLs
data_good_urls = data_remapped.groupby(["panelist_id", "bucket"]).filter(
    lambda x: x["domain"].notna().all()
)
print(f"Rows: {len(data_good_urls)}")
print(f"Number of possible traces: {len(data_good_urls.groupby(['panelist_id', 'bucket']))}")
data_good_urls.iloc[np.r_[0:5, -5:0]]

Rows: 126423
Number of possible traces: 5536

,panelist_id,web_visits_id,url,used_at,active_seconds,domain,bucket
0,0,112304243,791,2018-10-06 20:47:11,2,https://www.youtube.com/,281
1,0,112304243,214,2018-10-06 20:58:31,72,https://www.youtube.com/,281
2,0,112304243,791,2018-10-06 20:51:11,4,https://www.youtube.com/,281
3,0,112304243,114934,2018-10-06 20:35:50,42,https://www.youtube.com/,281
4,0,112304243,114936,2018-10-06 20:51:15,179,https://www.youtube.com/,281
215313,2147,118683408,1902996,2018-10-15 09:37:24,573,https://www.futurezone.de/,691
215314,2147,118683408,1902997,2018-10-15 09:47:32,74,https://www.futurezone.de/,691
215315,2147,118683408,1902996,2018-10-15 09:50:10,8,https://www.futurezone.de/,691
215316,2147,118683408,1902997,2018-10-15 09:48:50,80,https://www.futurezone.de/,691
215317,2147,118683408,1902996,2018-10-15 09:47:11,3,https://www.futurezone.de/,691

In [23]:
data_good_urls.to_csv(f"{OUTPUT_FOLDER}/cleaned_buckets.csv", index=False)

In [24]:
data_good_urls = pd.read_csv(
    f"{OUTPUT_FOLDER}/cleaned_buckets.csv",
    dtype={"id": int, "web_visits_id": int},
    parse_dates=["used_at"],
)

In [ ]:
def fake_links(domain):
    if "facebook.com" in domain:
        # facebook requires login so it is hard to discover real pages
        return [
            "https://www.facebook.com/Cristiano/",
            "https://www.facebook.com/SamsungUS/",
            "https://www.facebook.com/cgtnamerica/",
            "https://www.facebook.com/youtube/",
            "https://www.facebook.com/MrBean/",
            "https://m.facebook.com/shakira",
            "https://www.facebook.com/buzzfeedtasty",
            "https://www.facebook.com/netflixus/",
            "https://m.facebook.com/RealMadrid",
            "https://www.facebook.com/FCBFansNation/",
            "https://www.facebook.com/FCBFansNation/",
            "https://www.facebook.com/XinhuaNewsAgency/",
            "https://www.facebook.com/WillSmith",
            "https://www.facebook.com/chinadaily",
            "https://m.facebook.com/rihanna",
            "https://www.facebook.com/leomessi",
            "https://www.facebook.com/TheCocaColaCo/",
            "https://www.facebook.com/eminem/",
            "https://www.facebook.com/5MinuteCrafts",
            "https://www.facebook.com/uefachampionsleague",
        ]
    elif "youtube.com" in domain:
        # youtube is client-side rendered so scraping links is difficult
        return [
            "https://www.youtube.com/user/YouTube",
            "https://www.youtube.com/@MrBeast",
            "https://www.youtube.com/channel/UCbCmjCuTUZos6Inko4u57UQ",
            "https://www.youtube.com/channel/UCpEhnqL0y41EpW2TvWAHD7Q",
            "https://www.youtube.com/c/VladandNiki",
            "https://www.youtube.com/c/KidsDianaShow",
            "https://www.youtube.com/channel/UCJplp5SjeGSdVdwsfb9Q7lQ",
            "https://www.youtube.com/channel/UCbp9MyKCTEww4CxEzc_Tp0Q",
            "https://www.youtube.com/user/zeemusiccompany",
            "https://www.youtube.com/wwe",
            "https://www.youtube.com/watch?v=XqZsoesa55w",
            "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
            "https://www.youtube.com/watch?v=e_04ZrNroTo",
            "https://www.youtube.com/watch?v=WRVsOCh907o",
            "https://www.youtube.com/watch?v=F4tHL8reNCs",
            "https://www.youtube.com/watch?v=RgKAFK5djSk",
            "https://www.youtube.com/watch?v=JGwWNGJdvx8",
            "https://www.youtube.com/watch?v=hq3yfQnllfQ",
            "https://www.youtube.com/watch?v=9bZkp7q19f0",
            "https://www.youtube.com/watch?v=OPf0YbXqDm0",
        ]
    elif "twitter.com" in domain or "x.com" in domain:
        return [
            "https://twitter.com/elonmusk",
            "https://twitter.com/BarackObama",
            "https://twitter.com/realDonaldTrump",
            "https://twitter.com/katyperry",
            "https://twitter.com/justinbieber",
            "https://twitter.com/Cristiano",
            "https://twitter.com/TaylorSwift13",
            "https://twitter.com/Rihanna",
            "https://twitter.com/NASA",
            "https://twitter.com/BillGates",
            "https://twitter.com/ladygaga",
            "https://twitter.com/YouTube",
            "https://twitter.com/kimkardashian",
            "https://twitter.com/Oprah",
            "https://twitter.com/Drake",
            "https://twitter.com/realtrvismccoy",
            "https://twitter.com/selenagomez",
            "https://twitter.com/realmadrid",
            "https://twitter.com/FCBarcelona",
            "https://twitter.com/FCBayern",
        ]
    elif "instagram.com" in domain:
        return [
            "https://www.instagram.com/cristiano/",
            "https://www.instagram.com/samsungus/",
            "https://www.instagram.com/cgtnamerica/",
            "https://www.instagram.com/youtube/",
            "https://www.instagram.com/mrbean/",
            "https://www.instagram.com/shakira",
            "https://www.instagram.com/buzzfeedtasty",
            "https://www.instagram.com/realmadrid",
            "https://www.instagram.com/fcbfansnation/",
            "https://www.instagram.com/willsmith",
            "https://www.instagram.com/leomessi",
            "https://www.instagram.com/thecocacolaco/",
            "https://www.instagram.csom/eminem/",
            "https://www.instagram.com/elonofficiall/",
            "https://www.instagram.com/barackobama/",
            "https://www.instagram.com/justinbieber/",
            "https://www.instagram.com/katyperry/",
            "https://www.instagram.com/taylorswift/",
            "https://www.instagram.com/nasa/",
        ]
    elif "msn.com" in domain:
        return [
            "https://www.msn.com/en-us/video/peopleandplaces/i-built-a-1500hp-big-block-mustang-for-burnouts/vi-AA1yKJBq",
            "https://www.msn.com/en-us/news/politics/controversial-tax-provision-eliminated-from-trump-bill/ss-AA1I28T1",
            "https://www.msn.com/en-us/news/technology/us-advanced-ac-130-gunship-fires-all-its-scary-cannons-on-ground-targets/vi-AA1Fic4Q",
            "https://www.msn.com/en-us/money/realestate/the-whole-country-is-starting-to-look-like-california/ar-AA1HGyEy",
            "https://www.msn.com/en-us/news/technology/the-extreme-technique-used-by-us-aircraft-carriers-to-protect-each-other/vi-AA1EwoT6",
            "https://www.msn.com/en-us/lifestyle/smart-living/famous-last-words-from-15-iconic-people/ar-AA1E4z55",
            "https://www.msn.com/en-us/news/other/man-pardoned-for-jan-6-gets-life-in-prison-for-plotting-to-incite-civil-war-attack-fbi-agents/vi-AA1HVGSH",
            "https://www.msn.com/en-us/lifestyle/lifestyle-buzz/kate-middleton-s-gesture-at-surprise-engagement-is-right-out-of-princess-diana-s-playbook/ar-AA1I20Jq",
            "https://www.msn.com/en-us/news/politics/american-dystopia-the-cruel-spectacle-of-trump-s-alligator-alcatraz/vi-AA1I27LQ",
            "https://www.msn.com/en-us/weather/topstories/hundreds-of-campers-reunite-with-parents-after-deadly-guadalupe-river-flooding-we-didn-t-stop-to-sleep/ar-AA1I2LDF"
            "https://www.msn.com/en-us/channel/topic/Top%20Stories/tp-Y_46b78bbb-31c4-4fc5-8a4a-858072348d06"
            "https://www.msn.com/en-us/sports",
            "https://www.msn.com/en-us/play",
            "https://www.msn.com/en-us/money",
            "https://www.msn.com/en-us/video",
            "https://www.msn.com/en-us/tv/news/desi-arnaz-singer-husband-dad-and-the-man-who-invented-tv/vi-AA1GKPwv",
            "https://www.msn.com/en-us/money/retirement/i-ve-run-a-financial-independence-podcast-for-9-years-here-are-4-mistakes-i-see-early-retirees-make-all-the-time/ar-AA1FTrMM",
            "https://www.msn.com/en-us/money/retirement/how-much-is-the-required-minimum-distribution-rmd-if-you-have-500-000-in-your-retirement-account/ar-AA1x6ufB",
            "https://www.msn.com/en-us/news/world/a-tiny-town-in-india-s-himalayas-buzzes-with-activity-to-celebrate-dalai-lama-s-90th-birthday/ar-AA1I2Trq",
            "https://www.msn.com/en-us/travel/tripideas/20-small-towns-that-look-like-they-re-frozen-in-time/ar-AA1qxaFo",
        ]
    elif "twitch.tv" in domain:
        return [
            "https://www.twitch.tv/pewdiepie",
            "https://www.twitch.tv/ninja",
            "https://www.twitch.tv/shroud",
            "https://www.twitch.tv/asmongold",
            "https://www.twitch.tv/valkyrae",
            "https://www.twitch.tv/markiplier",
            "https://www.twitch.tv/streamerhouse",
            "https://www.twitch.tv/leagueoflegends",
            "https://www.twitch.tv/callofduty",
            "https://www.twitch.tv/fortnite",
            "https://www.twitch.tv/justchatting",
            "https://www.twitch.tv/riotgames",
            "https://www.twitch.tv/epicgames",
            "https://www.twitch.tv/valorant",
            "https://www.twitch.tv/auronplay",
            "https://www.twitch.tv/Rubius",
            "https://www.twitch.tv/ibai",
            "https://www.twitch.tv/xQc",
            "https://www.twitch.tv/Corpse_Husband",
            "https://www.twitch.tv/Tfue"
        ]
    else:
        return None

In [ ]:
MIN_DISTINCT_URLS = 7
MAX_DISTINCT_URLS = 20
MAX_TRIES = 150


async def validate_url(session, url):
    try:
        response = await session.get(url, headers=get_headers(url))
        await response.text()
        return response.url
    except Exception as e:
        if str(e):
            print(f"Error validating {url}: {e}")
        else:
            print(f"Error validating {url}: {repr(e)}")
        return None


class UrlGenerator:
    def __init__(self, landing_page, url_ids):
        self.landing_page = landing_page
        self.url_ids = url_ids
        self.url_map = None
        # Skip any domain where we can't find enough links
        self.invalid = False

    def resolve_url(self, url_id):
        return self.url_map[url_id]

    async def generate_map(self, session):
        if self.url_map is not None:
            return
        self.url_map = {}

        print(f"Generating URL map for {self.landing_page}, finding {len(self.url_ids)} links")

        try:
            response = await session.get(self.landing_page, headers=get_headers(self.landing_page))
            text = await response.text()
            soup = bs4.BeautifulSoup(text, "html.parser")

            # use manually curated links if applicable
            # otherwise, visit homepage and scrape random links
            selected_links = fake_links(self.landing_page)
            if not selected_links:
                links = [tag["href"] for tag in soup.find_all("a", href=True)]
                links = [urlparse(link) for link in links]
                landing = urlparse(self.landing_page)
                new_links = [url for url in links if url.path != landing.path and url.scheme in ["http", "https", ""]]
                prepared_links = []
                for link in new_links:
                    prepared_link = link
                    if not prepared_link.scheme:
                        prepared_link = prepared_link._replace(scheme=landing.scheme)
                    if not prepared_link.netloc:
                        prepared_link = prepared_link._replace(netloc=landing.netloc)
                    prepared_links.append(prepared_link)
                random.shuffle(prepared_links)
                prepared_links = prepared_links[:MAX_DISTINCT_URLS]

                desired_links = min(len(self.url_ids), MAX_DISTINCT_URLS)
                selected_links = set()
                link_index = 0
                while desired_links > 0:
                    if link_index >= len(prepared_links):
                        if len(prepared_links) < MIN_DISTINCT_URLS:
                            # ran out of links to examine
                            print(f"Page '{self.landing_page}' doesn't have enough links")
                            self.invalid = True
                            return
                        else:
                            # don't have enough links for unique mapping, but enough to continue
                            break
                    await asyncio.sleep(10)  # avoid the server rate limiting us

                    valid_link = await validate_url(session, urlunparse(prepared_links[link_index]))
                    link_index += 1
                    if valid_link and valid_link not in selected_links:
                        selected_links.add(valid_link)
                        desired_links -= 1
                selected_links = list(selected_links)

            selected_links.append(self.landing_page)
            selected_link_index = 0
            self.url_map = {}
            for url_id in self.url_ids:
                self.url_map[url_id] = selected_links[selected_link_index]
                selected_link_index += 1
                if selected_link_index >= len(selected_links):
                    selected_link_index = 0
            
            print(f"Finished generating URL map for {self.landing_page}")
        except Exception as e:
            if str(e):
                print(f"Error generating URL map for {self.landing_page}: {e}")
            else:
                print(f"Error generating URL map for {self.landing_page}: {repr(e)}")
            self.invalid = True

In [ ]:
url_generators = {}

counter = 0
for domain in data_good_urls["domain"].unique():
    url_ids = data_good_urls[data_good_urls["domain"] == domain]["url"].unique()
    url_generators[domain] = UrlGenerator(domain, url_ids)
    counter += 1
    if counter % 300 == 0:
        print(f"Created {counter} URL generators")

Created 300 URL generators
Created 600 URL generators
Created 900 URL generators
Created 1200 URL generators
Created 1500 URL generators
Created 1800 URL generators
Created 2100 URL generators
Created 2400 URL generators
Created 2700 URL generators
Created 3000 URL generators
Created 3300 URL generators
Created 3600 URL generators
Created 3900 URL generators
Created 4200 URL generators
Created 4500 URL generators
Created 4800 URL generators
Created 5100 URL generators

In [ ]:
async with aiohttp.ClientSession(
    connector=aiohttp.TCPConnector(
        ssl=False,
        keepalive_timeout=2,
        limit=150,
    ),
    raise_for_status=True,
    auto_decompress=True,
    timeout=aiohttp.ClientTimeout(total=None, sock_connect=10, sock_read=10),
) as session:
    await asyncio.gather(
        *(url_generator.generate_map(session) for url_generator in url_generators.values())
    )

Generating URL map for https://www.youtube.com/, finding 4985 links
Generating URL map for http://emedien3.sub.uni-hamburg.de, finding 1 links
Generating URL map for https://www.google.com/?gws_rd=ssl, finding 5266 links
Generating URL map for https://en.wikipedia.org/wiki/Main_Page, finding 35 links
Generating URL map for https://www.netflix.com/, finding 458 links
Generating URL map for https://de.wikipedia.org/wiki/Wikipedia:Hauptseite, finding 246 links
Generating URL map for https://www.spiegel.de/, finding 128 links
Generating URL map for https://www.al-monitor.com/, finding 1 links
Generating URL map for https://savoy.premiumkino.de, finding 1 links
Generating URL map for https://www.studio-kino.de/, finding 1 links
Generating URL map for https://www.kinoheld.de/, finding 1 links
Generating URL map for https://www.stine.uni-hamburg.de/, finding 10 links
Generating URL map for http://hp.myway.com/myway/index.html, finding 9 links
Generating URL map for https://www.amazon.de/, finding 3121 links
Generating URL map for https://www.paypal.com/us/home, finding 266 links
Generating URL map for https://www.gmx.net/, finding 656 links
Generating URL map for https://exchange.umwelt-campus.de/owa/auth/logon.aspx?url=https://exchange.umwelt-campus.de/owa&reason=0, finding 1 links
Generating URL map for https://www.studienkreis.de/, finding 2 links
Generating URL map for https://www.spreadshirt.de/, finding 11 links
Generating URL map for https://partner.spreadshirt.de/, finding 2 links
Generating URL map for https://us.plus500.com/en/, finding 1 links
Generating URL map for https://de.chaturbate.com/, finding 155 links
Generating URL map for https://chaturbate.com/, finding 2 links
Generating URL map for https://www.xnxx.com/, finding 133 links
Generating URL map for https://www.umwelt-campus.de/, finding 1 links
Generating URL map for https://qis.hochschule-trier.de/, finding 3 links
Generating URL map for https://www.netmoms.de/, finding 5 links
Generating URL map for https://bewerbungsschreiben.org/, finding 1 links
Generating URL map for https://www.startfenster.de/, finding 4 links
Generating URL map for https://www.spk-vorpommern.de/de/home.html, finding 14 links
Generating URL map for https://www.facebook.com/, finding 4456 links
Generating URL map for https://www.otto.de/, finding 236 links
Generating URL map for https://zoo.stralsund.de/, finding 2 links
Generating URL map for https://vapi.intapi.com/login, finding 57 links
Generating URL map for https://www.t-online.de/?top, finding 387 links
Generating URL map for https://www.t-online.de/, finding 172 links
Generating URL map for http://tierheim-gotha.net, finding 7 links
Generating URL map for https://translate.google.com/, finding 88 links
Generating URL map for https://escalent.co, finding 27 links
Generating URL map for https://www.tiervermittlung.de/, finding 5 links
Generating URL map for https://www.klebefieber.de/, finding 14 links
Generating URL map for https://plus.rtl.de/, finding 235 links
Generating URL map for https://webshop-consorsfinanz.de/, finding 3 links
Generating URL map for https://www.magdeburg.de/, finding 4 links
Generating URL map for https://dirtyroulette.com/, finding 1 links
Generating URL map for https://www.mvbnet.de/, finding 5 links
Generating URL map for https://login.aol.com/, finding 118 links
Generating URL map for https://mail.aol.com/, finding 15 links
Generating URL map for https://www.aol.de/, finding 4 links
Generating URL map for https://www.aponeo.de/, finding 16 links
Generating URL map for http://kinox.io, finding 6 links
Generating URL map for http://ww25.streamcloud.eu/?subid1=20250704-0913-1648-b80b-74fdb42d4940, finding 7 links
Generating URL map for https://ww21.kinos.to/, finding 7 links
Generating URL map for https://accounts.google.com/v3/signin/identifier?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&ifkv=AdBytiNswLCoChNS9aU3ktmL5iczxjrY7isYJospbcFRbmKJHU7Xf7KalDs_mgTmDH6B2QXDcaLV&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-117077236:1751584397066078, finding 1194 links
Generating URL map for https://login.die-kleine-kamera.de/login, finding 1 links
Generating URL map for https://mail.yahoo.com/, finding 616 links
Generating URL map for https://www.sheetmusicdirect.com/Errors/SiteError.htm, finding 1 links
Generating URL map for https://www.musicnotes.com/, finding 1 links
Generating URL map for https://www.letternoteplayer.com/, finding 1 links
Generating URL map for https://www.ultimate-guitar.com/explore, finding 47 links
Generating URL map for https://www.ultimate-guitar.com/, finding 35 links
Generating URL map for https://havag.com/, finding 3 links
Generating URL map for https://results.searchlock.com/, finding 10 links
Generating URL map for https://www.abendblatt.de/, finding 2 links
Generating URL map for https://bellotube.com/, finding 4 links
Generating URL map for https://ge.xhamster.com, finding 283 links
Generating URL map for https://de.pornhub.com/, finding 345 links
Generating URL map for https://hugesex.tv/en, finding 1 links
Generating URL map for https://www.pornoxo.com/, finding 1 links
Generating URL map for https://www.pornmd.com/, finding 1 links
Generating URL map for https://www.youporn.com/, finding 169 links
Generating URL map for http://nastyvideotube.com, finding 5 links
Generating URL map for https://txxx.com/, finding 20 links
Generating URL map for https://www.wikipedia.de/, finding 1 links
Generating URL map for https://www.zdf.de/, finding 53 links
Generating URL map for https://www.spektrum.de/, finding 5 links
Generating URL map for https://www.ardmediathek.de/, finding 52 links
Generating URL map for https://s07.ssd.neuit.de/, finding 1 links
Generating URL map for https://www.startseite24.net/, finding 1 links
Generating URL map for https://www.surveygizmo.com/, finding 3 links
Generating URL map for https://www.brutto-netto-rechner.info/, finding 1 links
Generating URL map for https://web.de/, finding 1468 links
Generating URL map for https://www.bild.de/, finding 180 links
Generating URL map for https://s.to/, finding 15 links
Generating URL map for https://accounts.google.com/v3/signin/identifier?continue=https://accounts.google.com/&followup=https://accounts.google.com/&ifkv=AdBytiPEnjMFYe6BZZux4_GMcHr8-1U_FvtWdiaigaFr1yGh9tbNVNPp37TCFBG5FwotL2EIdTMYfg&passive=1209600&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-316233113:1751584396977553, finding 198 links
Generating URL map for https://www.maingau-energie.de/, finding 2 links
Generating URL map for https://www.dkb.de/, finding 49 links
Generating URL map for https://www.comdirect.de/cms/index.html?CIF_Check=true, finding 6 links
Generating URL map for https://www.videobuster.de/, finding 9 links
Generating URL map for https://www.areadvd.de/, finding 1 links
Generating URL map for https://www.filmstarts.de/, finding 12 links
Generating URL map for https://www.cashbackdeals.de/, finding 45 links
Generating URL map for https://www.blau.de/, finding 7 links
Generating URL map for http://blurayreviews.ch, finding 2 links
Generating URL map for https://blu-ray-rezensionen.net/, finding 3 links
Generating URL map for http://www.serienjunkies.de/, finding 21 links
Generating URL map for http://convert2mp3.net, finding 29 links
Generating URL map for https://outlook.live.com/mail/0/, finding 700 links
Generating URL map for https://mrantifun.net/, finding 1 links
Generating URL map for https://gamecopyworld.com/games/index.php, finding 9 links
Generating URL map for https://www.mcafee.com, finding 1 links
Generating URL map for http://activetect.net, finding 6 links
Generating URL map for https://gamecopyworld.eu/games/index.php, finding 4 links
Generating URL map for https://www.gamepressure.com/, finding 2 links
Generating URL map for https://www.queer.de/, finding 4 links
Generating URL map for https://workspaceupdates.googleblog.com/2023/04/new-community-features-for-google-chat-and-an-update-currents%20.html, finding 8 links
Generating URL map for https://www.bvg.de/en/connections/connection-search, finding 5 links
Generating URL map for https://www.fotocollagen.de/, finding 1 links
Generating URL map for https://www.tumblr.com/, finding 24 links
Generating URL map for https://partnernet.amazon.de/, finding 3 links
Generating URL map for https://www.adcell.de/, finding 26 links
Generating URL map for https://www.gayporntube.com/, finding 26 links
Generating URL map for https://feedbaxx.de/, finding 28 links
Generating URL map for http://survey.r-c-online.com, finding 12 links
Generating URL map for https://www.instantresearch.cz/, finding 5 links
Generating URL map for https://app.enlight.ly/, finding 2 links
Generating URL map for http://i24.cc, finding 6 links
Generating URL map for https://www.slicethepie.com/, finding 6 links
Generating URL map for https://paidlikes.de/, finding 3 links
Generating URL map for https://anonym.to/, finding 2 links
Generating URL map for http://perscheck.safe-ws.eu, finding 1 links
Generating URL map for https://www.sparda-west.de/, finding 11 links
Generating URL map for https://www.kleinanzeigen.de/?utm_source=ekde, finding 560 links
Generating URL map for https://kunde.trend-research.de/, finding 12 links
Generating URL map for https://www.techniropa.de/, finding 1 links
Generating URL map for https://accounts.google.com/v3/signin/identifier?continue=https://mail.google.com/chat/u/0/&followup=https://mail.google.com/chat/u/0/&ifkv=AdBytiN2WOPoLElFT7bKUdUgqpQYRk_0iLaDqPAfJnZ9qKmxAVEkjw0Patr2pT_-RdW_FjJ59wkH5w&osid=1&passive=1209600&service=dynamite&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S976812362:1751584421899990, finding 3 links
Generating URL map for https://www.conrad.de/, finding 29 links
Generating URL map for https://www.reddit.com/, finding 12 links
Generating URL map for https://www.ea.com/games/library/pc-download, finding 1 links
Generating URL map for https://www.mikrocontroller.net/, finding 2 links
Generating URL map for https://www.pollin.de/, finding 4 links
Generating URL map for https://www.pcgameshardware.de/, finding 5 links
Generating URL map for https://news.google.com/home?hl=en-US&gl=US&ceid=US:en, finding 20 links
Generating URL map for https://www.westermanngruppe.de/, finding 1 links
Generating URL map for https://www.eurobuch.de/, finding 1 links
Generating URL map for https://www.hopp-marktforschung.de/, finding 26 links
Generating URL map for https://net-request.de/, finding 3 links
Generating URL map for https://www.welt.de/, finding 44 links
Generating URL map for https://www.waterdrop.com/, finding 1 links
Generating URL map for https://www.4tube.com/, finding 1 links
Generating URL map for https://www.twitch.tv/, finding 82 links
Generating URL map for https://www.bahn.de/, finding 186 links
Generating URL map for https://shop.flixbus.de/, finding 21 links
Generating URL map for https://aws.amazon.com/, finding 30 links
Generating URL map for https://n26.com/en-us, finding 13 links
Generating URL map for https://www.freenet.de/, finding 48 links
Generating URL map for https://www.flixbus.com, finding 6 links
Generating URL map for https://www.sparda-b.de/homepage.html, finding 17 links
Generating URL map for http://unsubscribe.use.cc, finding 1 links
Generating URL map for https://nielseniq.com/global/en/, finding 78 links
Generating URL map for http://my.stampinup.com, finding 4 links
Generating URL map for https://www.stampinup.com/, finding 3 links
Generating URL map for https://www.zeit.de/index, finding 42 links
Generating URL map for https://de-de.facebook.com/, finding 14 links
Generating URL map for https://www.wundermix.de/, finding 1 links
Generating URL map for https://thecraftspa.blogspot.com/, finding 1 links
Generating URL map for https://www.instagram.com/, finding 147 links
Generating URL map for https://martinaziehlmitpamperedchef.de/, finding 3 links
Generating URL map for http://martinaziehl.blogspot.com, finding 3 links
Generating URL map for https://addons.mozilla.org/en-US/firefox/, finding 11 links
Generating URL map for https://www.markt.de/, finding 25 links
Generating URL map for https://www.meinungsclub.de/, finding 12 links
Generating URL map for https://mylittlefarmies.upjers.com/de/, finding 4 links
Generating URL map for https://de.upjers.com/, finding 5 links
Generating URL map for http://newsletter.bofrost.info, finding 1 links
Generating URL map for https://www.parship.de/, finding 18 links
Generating URL map for https://www.hypovereinsbank.de/hvb/privatkunden, finding 2 links
Generating URL map for https://www.1822direkt.de/, finding 2 links
Generating URL map for https://www.booklooker.de/, finding 72 links
Generating URL map for https://www.microsoft.com/en-us/privacy, finding 1 links
Generating URL map for http://www.microsoft.com/, finding 12 links
Generating URL map for https://www.comodo.com/, finding 1 links
Generating URL map for https://support.google.com/, finding 21 links
Generating URL map for https://transparencyreport.google.com/, finding 2 links
Generating URL map for https://www.sparkasse.de/, finding 9 links
Generating URL map for https://www.sskm.de/de/home.html, finding 2 links
Generating URL map for https://www.check24.de/, finding 163 links
Generating URL map for https://metalmailorder.com/, finding 1 links
Generating URL map for https://www.cudgel.de/, finding 1 links
Generating URL map for https://www.nuclearblast.com/de, finding 3 links
Generating URL map for https://www.barmer.de/, finding 35 links
Generating URL map for https://shop-hellsheadbangers.com/, finding 7 links
Generating URL map for https://www.stern.de/, finding 78 links
Generating URL map for https://banking.postbank.de/, finding 169 links
Generating URL map for https://www.yelp.de/san-jose, finding 8 links
Generating URL map for https://www.spiegel.de/start/, finding 1 links
Generating URL map for https://www.wiso-net.de/?targetUrl=/, finding 1 links
Generating URL map for https://www.arte.tv/en/, finding 5 links
Generating URL map for https://www.divibib.com/informationen-fuer-nutzerinnen/c-1819, finding 7 links
Generating URL map for https://www.divibib.com/, finding 4 links
Generating URL map for https://toledo.kuleuven.be/, finding 1 links
Generating URL map for https://web.telegram.org/, finding 8 links
Generating URL map for http://owa.student.kuleuven.be, finding 3 links
Generating URL map for http://www.bing.com/, finding 470 links
Generating URL map for https://www.booking.com, finding 35 links
Generating URL map for https://www.booking.com/, finding 177 links
Generating URL map for https://der-farang.com/de, finding 12 links
Generating URL map for https://mega.nz, finding 2 links
Generating URL map for https://www.nutaku.net/, finding 3 links
Generating URL map for https://pr0gramm.com/, finding 3 links
Generating URL map for https://cuntwars.com/, finding 1 links
Generating URL map for https://www.sport1.de/, finding 49 links
Generating URL map for https://www.extratipp.com/, finding 2 links
Generating URL map for https://poloniex.com/, finding 11 links
Generating URL map for https://www.essen-und-trinken.de/, finding 14 links
Generating URL map for https://www.chefkoch.de/, finding 127 links
Generating URL map for http://www.bildschirmarbeiter.com/, finding 1 links
Generating URL map for https://vimeo.com/, finding 16 links
Generating URL map for https://gewinnen-roulette.de, finding 1 links
Generating URL map for https://www.vfv06.de/, finding 2 links
Generating URL map for https://www.voicefive.com/Home.aspx, finding 5 links
Generating URL map for https://roundcube.hhu.de/, finding 2 links
Generating URL map for https://umfragen.intquest.de/, finding 3 links
Generating URL map for https://www.mymarktforschung.de/de/, finding 1 links
Generating URL map for https://surveys.mymarktforschung.de/, finding 13 links
Generating URL map for https://www.mars.com/contact-us, finding 10 links
Generating URL map for https://www.chip.de/, finding 49 links
Generating URL map for https://www.123test.com/de/, finding 9 links
Generating URL map for https://www.wish.com/, finding 75 links
Generating URL map for https://nationalgeographic.de/, finding 2 links
Generating URL map for https://www.rtl.de/, finding 6 links
Generating URL map for https://ga.de/, finding 5 links
Generating URL map for https://augenklinik.uk-koeln.de/, finding 6 links
Generating URL map for https://www.topeleven.com/, finding 1 links
Generating URL map for https://www.diesiedleronline.de/de, finding 8 links
Generating URL map for https://adfs.ebz-group.com/adfs/ls?version=1.0&action=signin&realm=urn:AppProxy:com&appRealm=b5e05e46-fdf6-e911-90ff-00155d60b08f&returnUrl=https://outlook.ebz-group.com/owa&client-request-id=4BC12CB4-C67A-0001-8AB3-224C7AC6DB01, finding 5 links
Generating URL map for https://www.affaire.com/, finding 4 links
Generating URL map for https://www.jackpot.de/, finding 18 links
Generating URL map for https://millionenklick.gmx.net/, finding 7 links
Generating URL map for https://www.ndr.de/, finding 21 links
Generating URL map for https://de.search.yahoo.com/, finding 54 links
Generating URL map for https://nur.xxx/, finding 2 links
Generating URL map for https://xxxcj.com/, finding 3 links
Generating URL map for https://pornq.com/, finding 3 links
Generating URL map for https://www.3movs.com/, finding 12 links
Generating URL map for https://www.bangbrosnetwork.com/, finding 2 links
Generating URL map for https://faptitans.com/age_verify/?s=1, finding 8 links
Generating URL map for https://hotmovs.com/, finding 7 links
Generating URL map for https://de.mydirtyhobby.com/, finding 1 links
Generating URL map for https://www.myhermes.de/, finding 18 links
Generating URL map for https://www.1und1.de/, finding 122 links
Generating URL map for https://www.gutefrage.net/, finding 50 links
Generating URL map for https://de.pinterest.com/, finding 132 links
Generating URL map for https://debeste.de/, finding 4 links
Generating URL map for https://online.sovendus.com/, finding 16 links
Generating URL map for https://www.dhl.de/de/privatkunden.html, finding 45 links
Generating URL map for https://www.porn.com/, finding 24 links
Generating URL map for https://www.smarticular.net/, finding 2 links
Generating URL map for https://www.gartenjournal.net/, finding 3 links
Generating URL map for https://www.kostbarenatur.net/, finding 1 links
Generating URL map for https://www.eporner.com/, finding 26 links
Generating URL map for https://www.windows-10-forum.com/, finding 2 links
Generating URL map for https://www.pcwelt.de, finding 18 links
Generating URL map for https://play.google.com/store/games, finding 34 links
Generating URL map for https://www.dropbox.com/, finding 50 links
Generating URL map for https://www.apple.com/itunes/, finding 6 links
Generating URL map for https://www.optamassivhaus.com/, finding 15 links
Generating URL map for https://www.viebrockhaus.de/, finding 5 links
Generating URL map for https://gameforge.com/, finding 49 links
Generating URL map for https://www.wort-suchen.de/, finding 15 links
Generating URL map for https://kunde.comdirect.de/lp/wt/login?execution=e1s1&afterTimeout=true, finding 107 links
Generating URL map for https://survey.dubiku.de/, finding 6 links
Generating URL map for https://www.targobank.de/de/index.html, finding 63 links
Generating URL map for https://www.misterspex.de/, finding 44 links
Generating URL map for https://www.ea.com/sports, finding 2 links
Generating URL map for https://www.frankfurter-volksbank.de/privatkunden.html, finding 24 links
Generating URL map for https://www.promiflash.de/, finding 4 links
Generating URL map for https://nametests.com/, finding 12 links
Generating URL map for https://www.immobilienscout24.de/, finding 144 links
Generating URL map for https://www.kino.de/, finding 8 links

CancelledError:

In [ ]:
MAX_BATCH_SIZE = 50

data_prepared = data_good_urls.copy()
data_prepared["page"] = data_prepared["url"]
data_prepared["trace"] = 0
groups = [df for _, df in data_prepared.groupby(["panelist_id", "bucket"])]
random.shuffle(groups)

def remap_group(group, trace_id):
    group["trace"] = trace_id
    mapping = {}
    for domain in group["domain"].unique():
        filtered = group[group["domain"] == domain]
        for url_id in filtered["url"].unique():
            mapping[url_id] = url_generators[domain].resolve_url(url_id)
    group["page"] = group["page"].map(mapping)
    return group

traces = []
group_index = 0
while True:
    batch_size = min(MAX_BATCH_SIZE, DESIRED_TRACES - len(traces))
    if batch_size <= 0:
        break

    async with aiohttp.ClientSession(
        connector=aiohttp.TCPConnector(
            ssl=False,
            keepalive_timeout=2,
            limit=batch_size * 2,
        ),
        raise_for_status=True,
        auto_decompress=True,
        timeout=aiohttp.ClientTimeout(total=None, sock_connect=10, sock_read=10),
    ) as session:
        promises = []
        for group in groups[group_index:group_index + batch_size]:
            for domain in group["domain"].unique():
                promises.append(url_generators[domain].generate_map(session))
        await asyncio.gather(*promises)

        for group in groups[group_index:group_index + batch_size]:
            for domain in group["domain"].unique():
                if url_generators[domain].invalid:
                    break
            else:
                remapped = remap_group(group, len(traces) + 1)
                traces.append(remapped)
        group_index += batch_size

        print(f"Processed {len(traces)}/{DESIRED_TRACES} traces so far")
        await asyncio.sleep(5)

Generating URL map for http://owa.student.kuleuven.be, finding 3 links
Generating URL map for https://toledo.kuleuven.be/, finding 1 links
Generating URL map for https://www.youtube.com/, finding 4985 links
Generating URL map for https://www.facebook.com/, finding 4456 links
Generating URL map for https://www.farmerama.com/?originalURL=farmerama.com&, finding 28 links
Generating URL map for https://faptitans.com/age_verify/?s=1, finding 8 links
Generating URL map for https://www.eventit.ag/, finding 6 links
Generating URL map for https://onlinebewerbung.eventit.ag/, finding 1 links
Generating URL map for https://jobs.eventit.ag/, finding 1 links
Generating URL map for https://www.google.com/?gws_rd=ssl, finding 5266 links
Generating URL map for https://www.vgh-stiftung.de/, finding 1 links
Generating URL map for https://www.gutefrage.net/, finding 50 links
Generating URL map for https://www.helpster.de/, finding 3 links
Generating URL map for https://sportbild.bild.de/, finding 3 links
Generating URL map for https://www.sparkasse-mittelthueringen.de/de/home.html, finding 4 links
Generating URL map for https://bon-einloesen.de/, finding 2 links
Generating URL map for https://www.amazon.de/, finding 3121 links
Generating URL map for https://www.ran.de, finding 7 links
Generating URL map for https://www.kicker.de/, finding 72 links
Generating URL map for https://www.mdr.de/nachrichten/index.html, finding 17 links
Generating URL map for https://outlook.live.com/mail/0/, finding 700 links
Generating URL map for https://kdp.amazon.com/en_US/, finding 3 links
Generating URL map for https://www.amazon.com/ap/signin?openid.pape.preferred_auth_policies=Singlefactor&openid.pape.max_auth_age=900&openid.return_to=https://account.kdp.amazon.com/&openid.identity=http://specs.openid.net/auth/2.0/identifier_select&openid.assoc_handle=amzn_dtp&openid.mode=checkid_setup&language=en_US&openid.claimed_id=http://specs.openid.net/auth/2.0/identifier_select&pageId=kdp-ap&openid.ns=http://specs.openid.net/auth/2.0, finding 2 links
Generating URL map for https://windowsarea.de/, finding 1 links
Generating URL map for https://www.dpd.com/de/de/, finding 10 links
Generating URL map for https://de.wikipedia.org/wiki/Wikipedia:Hauptseite, finding 246 links
Generating URL map for http://www.bing.com/, finding 470 links
Generating URL map for https://www.werbeservice.de/, finding 1 links
Generating URL map for https://www.eis.de/, finding 68 links
Generating URL map for http://trendysachen.com, finding 1 links
Generating URL map for https://www.leben-und-erziehen.de/eltern-empfehlen?utm_source=redirect_service&utm_medium=redirect&utm_campaign=redirect_service, finding 3 links
Generating URL map for http://surveys.touchstone360.com, finding 64 links
Generating URL map for http://innocent.cspace.com, finding 3 links
Generating URL map for https://conceptsauce.com/, finding 19 links
Generating URL map for https://doodle.com/en/, finding 4 links
Generating URL map for https://tele5.de/, finding 2 links
Generating URL map for https://www.juniper.net/, finding 1 links
Generating URL map for https://play.funk.net/, finding 4 links
Generating URL map for https://jasbee.de/, finding 17 links
Generating URL map for https://web.de/, finding 1468 links
Generating URL map for https://www.sparkasse-oberlausitz-niederschlesien.de/de/home.html, finding 11 links
Generating URL map for https://www.dm.de/, finding 112 links
Generating URL map for https://de-play.forgeofempires.com, finding 16 links
Generating URL map for https://pomadeshop.com/, finding 12 links
Generating URL map for https://mail.yahoo.com/, finding 616 links
Generating URL map for https://mail.yahoo.com/d, finding 34 links
Generating URL map for https://accounts.google.com/v3/signin/identifier?continue=https://accounts.google.com/&followup=https://accounts.google.com/&ifkv=AdBytiPEnjMFYe6BZZux4_GMcHr8-1U_FvtWdiaigaFr1yGh9tbNVNPp37TCFBG5FwotL2EIdTMYfg&passive=1209600&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-316233113:1751584396977553, finding 198 links
Generating URL map for https://www.rs2.de/, finding 2 links
Generating URL map for https://uni-goettingen.de/, finding 1 links
Generating URL map for https://www.essen-und-trinken.de/, finding 14 links
Generating URL map for https://www.sms-hm.de/de/home.html, finding 3 links
Generating URL map for https://www.thalia.de/, finding 41 links
Generating URL map for https://mytolino.com/, finding 7 links
Generating URL map for https://secure.ogone.com/Ncol/Prod/Backoffice/login/index?branding=OGONE&error=login_required&state=4cc60648-5ec8-49ba-bae5-73a3e52e1bd8, finding 10 links
Generating URL map for https://www.paypal.com/us/home, finding 266 links
Generating URL map for https://www.daydreams.de/, finding 1 links
Generating URL map for https://www.msn.com/, finding 245 links
Generating URL map for https://www.zdf.de/, finding 53 links
Generating URL map for https://ajs.bocholt.de/, finding 6 links
Generating URL map for https://www.fotoparadies.de/, finding 18 links
Generating URL map for https://kapu-bocholt.de/, finding 1 links
Generating URL map for https://accounts.google.com/v3/signin/identifier?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&ifkv=AdBytiNswLCoChNS9aU3ktmL5iczxjrY7isYJospbcFRbmKJHU7Xf7KalDs_mgTmDH6B2QXDcaLV&osid=1&passive=1209600&service=mail&flowName=GlifWebSignIn&flowEntry=ServiceLogin&dsh=S-117077236:1751584397066078, finding 1194 links
Generating URL map for https://www.lvz.de/, finding 8 links
Generating URL map for https://foodsharing.de/, finding 11 links
Generating URL map for http://1tracking.net, finding 1 links
Generating URL map for https://www.fernuni-hagen.de/, finding 89 links
Generating URL map for https://www.dropbox.com/, finding 50 links
Generating URL map for https://www.gmx.net/, finding 656 links
Generating URL map for https://passwort.gmx.net/passwordrecovery/wicket/page?1&srttkn=b6d09245-b3f7-427c-8b34-677d01652039, finding 6 links
Generating URL map for https://suche.web.de/web, finding 75 links
Generating URL map for https://www.berliner-volksbank.de/start.html, finding 21 links
Generating URL map for https://service.deutschlandsim.de/, finding 5 links
Generating URL map for https://www.berlin.de/, finding 14 links
Generating URL map for https://service.berlin.de/, finding 6 links
Generating URL map for http://s156-de.ogame.gameforge.com, finding 14 links
Generating URL map for https://gameforge.com/, finding 49 links
Generating URL map for https://www.deezer.com/us/, finding 13 links
Generating URL map for https://arbgtr.justiz.rlp.de/, finding 1 links
Generating URL map for http://mailing.dhl.de, finding 7 links
Generating URL map for https://www.dhl.de/de/privatkunden.html, finding 45 links
Generating URL map for https://www.bunte.de/, finding 12 links
Generating URL map for https://www.oeffnungszeitenbuch.de/, finding 1 links
Generating URL map for https://www.ilias.fh-dortmund.de/ilias/login.php, finding 10 links
Generating URL map for https://www.heise.de/, finding 17 links
Generating URL map for https://www.aldi-nord.de/, finding 7 links
Generating URL map for https://de.pornhub.com/, finding 345 links
Generating URL map for https://de.yahoo.com/, finding 31 links
Generating URL map for https://savanta.com/, finding 1 links
Generating URL map for http://glosbe.com, finding 1 links
Generating URL map for https://www.duolingo.com/, finding 21 links
Generating URL map for https://de.duolingo.com/, finding 2 links
Generating URL map for https://www.lebensmittelzeitung.net/, finding 3 links
Generating URL map for https://www.lzmedien.net/werbeumfelder/event-sponsoring/, finding 5 links
Generating URL map for https://www.tedi.com/, finding 2 links
Generating URL map for https://woolworth.de/, finding 3 links
Generating URL map for http://survey2.gdp-group.com, finding 101 links
Generating URL map for https://www.dasoertliche.de/, finding 15 links
Generating URL map for https://www.ard.de/, finding 6 links
Generating URL map for https://www.daserste.de/, finding 11 links
Generating URL map for https://www.mopo.de/, finding 8 links
Generating URL map for https://www.sparkasse-nordschwaben.de/de/home.html, finding 8 links
Generating URL map for https://www.immobilienscout24.de/, finding 144 links
Generating URL map for https://mail.aol.com/, finding 15 links
Generating URL map for https://der-farang.com/de, finding 12 links
Generating URL map for https://de.search.yahoo.com/, finding 54 links
Generating URL map for https://de.style.yahoo.com/, finding 9 links
Generating URL map for https://www.meldebox.de/, finding 2 links
Generating URL map for http://xn--ffnungszeit-qfb.net, finding 1 links
Generating URL map for https://www.bornheim.de/, finding 2 links
Generating URL map for https://www.ombplus.de/ombplus/public/index.html, finding 5 links
Generating URL map for https://studip.uni-rostock.de/index.php, finding 16 links
Generating URL map for https://mathe-online.at/, finding 2 links
Generating URL map for https://mathics.org/, finding 1 links
Generating URL map for https://us.sofatutor.com/, finding 12 links
Generating URL map for https://www.spiegel.de/, finding 128 links
Generating URL map for https://www.vattenfall.de/, finding 23 links
Generating URL map for https://select.klassikradio.de/de, finding 1 links
Generating URL map for https://www.geo.de/, finding 1 links
Generating URL map for https://www.tripadvisor.de/, finding 47 links
Generating URL map for https://soundcloud.com/, finding 9 links
Generating URL map for https://peggo.online, finding 7 links
Generating URL map for https://www.sneakerprofi.de/, finding 6 links
Generating URL map for https://praxistipps.chip.de/, finding 20 links
Generating URL map for https://www.chip.de/, finding 49 links
Generating URL map for https://sedo.com/search/details/?partnerid=324561&language=us&domain=generationsmart.de&origin=sales_lander_15&utm_medium=Parking&utm_campaign=offerpage, finding 1 links
Generating URL map for https://ww21.kinos.to/, finding 7 links
Generating URL map for http://ww25.streamcloud.eu/?subid1=20250704-0913-1648-b80b-74fdb42d4940, finding 7 links
Generating URL map for https://www.betternet.co/, finding 1 links
Validating https://www.leben-und-erziehen.de/eltern-empfehlen-seite-5.html
Validating https://login.yahoo.com/account/create?src=ym-oasis&pspid=1197806870&activity=new-yahoo-account&ncid=100001767&.done=https%3A%2F%2Fmail.yahoo.com%3Fsrc%3Dym-oasis%26activity%3Dnew-yahoo-account%26ncid%3D100001767
Validating https://de.wikipedia.org/wiki/Wikipedia:Exzellente_Artikel
Page 'https://tele5.de/' doesn't have enough links
Validating http://www.bing.com/news/search?q=Top+stories&nvaug=%5bNewsVertical+Category%3d%22rt_MaxClass%22%5d&FORM=Z9LH3
Error generating URL map for https://www.thalia.de/: 403, message='Forbidden', url='https://www.thalia.de/'
Validating https://guce.yahoo.com/terms?locale=en-US
Validating https://www.juniper.net/us/en/products/security/security-director-network-security-management.html
Finished generating URL map for https://www.msn.com/
Page 'https://outlook.live.com/mail/0/' doesn't have enough links
Validating https://ai.google/societal-impact/?utm_source=googlehpfooter&utm_medium=housepromos&utm_campaign=bottom-footer
Validating https://www.aldi-nord.de/angebote/aktion-mo-07-07/frucht-joghurt-792-0-0.article.html
Validating https://www.helpster.de/beauty-styling/frisuren-9811
Validating https://www.kicker.de/schnellfragerunde-mit-den-dfb-frauen-1128456/video
Finished generating URL map for https://www.facebook.com/
Page 'http://trendysachen.com' doesn't have enough links
Validating https://accounts.google.com/TOS?loc=US&hl=en-US&privacy=true
Page 'http://innocent.cspace.com' doesn't have enough links
Validating https://www.ran.de/sports/fussball/news/fc-bayern-muenchen-bestuerzt-und-schockiert-trainer-bricht-bei-fussball-camp-zusammen-556136
Validating https://accounts.google.com/TOS?loc=US&hl=en-US
Validating http://www.amazon.com/gp/help/customer/display.html/ref=footer_cou?ie=UTF8&nodeId=508088
Validating https://kdp.amazon.com/help/topic/G201834330
Validating https://account.deezer.com/en-us/signup/
Validating http://microsoft365.com/start/PowerPoint.aspx?WT.mc_id=O16_BingHP
Page 'http://1tracking.net' doesn't have enough links
Validating https://www.mopo.de#content-wrapper
Validating https://www.bunte.de/beauty/
Validating https://de.wikipedia.org/wiki/Datei:3I-ATLAS_CFHT_2025-Jul-02_Seligman_et_al._2025_crop-invert.png
Validating https://de.yahoo.com/nachrichten/trauerfeier-portugal-diogo-jotas-witwe-103018611.html
Finished generating URL map for https://www.youtube.com/
Validating https://www.dasoertliche.de/Personensuche/Nachnamen-D
Validating https://www.facebook.com/farmerama/
Validating http://glosbe.com/ru/zh/%D1%81%D0%BE%D0%BA%D1%80%D0%BE%D0%B2%D0%B8%D1%89%D0%B5%E5%90%8D%E8%A9%9E%28%E5%8F%97%E8%A9%9E%29%E5%AF%B6%E8%97%8F,%E4%B8%AD%E6%80%A7%E5%90%8D%E8%A9%9E,%E9%80%99%E8%A3%A1%E6%98%AF%E5%8F%A5%E5%AD%90%E7%9A%84%E8%B3%93%E8%AA%9E
Validating https://doodle.com/en/why-doodle/
Validating https://www.essen-und-trinken.de/rezepte/schneller-tomaten-pfirsich-salat-mit-ricotta-14011416.html
Page 'https://faptitans.com/age_verify/?s=1' doesn't have enough links
Validating https://www.paypal.com/us/privacy-center/home
Validating http://www.gdp-group.com/
Validating https://sportbild.bild.de/bundesliga/vereine/sv-darmstadt-98/home-41559426.sport.html
Validating http://manpages.debian.org/cgi-bin/man.cgi?query=a2disconf
Finished generating URL map for https://www.juniper.net/
Validating https://www.leben-und-erziehen.de/eltern-empfehlen/woom-fahrrad-test-14508.html
Validating https://mopop.de/konzerte/oasis-sind-zurueck-so-lief-das-comeback-konzert-der-britpop-koenige-29591
Page 'https://de.duolingo.com/' doesn't have enough links
Validating https://www.ran.de/sports/basketball/nba/videos/nba-highlights-oklahoma-city-thunder-schlagen-portland-trail-blazers
Validating https://fr.wikipedia.org/wiki/
Finished generating URL map for https://www.dropbox.com/
Validating http://windowsarea.de/forum/
Validating https://de.pornhub.com/transgender
Page 'https://www.duolingo.com/' doesn't have enough links
Page 'https://www.ard.de/' doesn't have enough links
Page 'https://www.dm.de/' doesn't have enough links
Validating https://www.amazon.de/gp/help/customer/display.html?nodeId=202024860&ref_=footer_impressum
Validating https://www.bunte.de/royals/schwedisches-koenigshaus/
Validating https://legal.bigpoint.com/terms-and-conditions/en
Validating https://www.kicker.de/knaller-von-martinelli-purer-wille-von-hercules-fluminense-im-halbfinale-1129715/video
Validating https://doodle.com/en/solutions/sales/
Page 'http://surveys.touchstone360.com' doesn't have enough links
Error generating URL map for https://passwort.gmx.net/passwordrecovery/wicket/page?1&srttkn=b6d09245-b3f7-427c-8b34-677d01652039: 401, message='401', url='https://passwort.gmx.net/passwordrecovery/wicket/page?1&srttkn=b6d09245-b3f7-427c-8b34-677d01652039'
Validating https://www.gutefrage.net/umfrage/stimmt-es-das-ab-und-zu-den-motor-auf-volllast-fahren-sollte
Validating https://www.dhl.de/de/privatkunden/hilfe-kundenservice/versenden/preise-produkte.html
Validating https://play.funk.net/playlist/neuesteVideos/er-filmt-wenns-geknallt-hat-so-arbeitet-ein-blaulichtreporter-die-andere-frage-2077328
Validating https://www.leben-und-erziehen.de/schwangerschaft/geburt/glueckwuensche-zur-geburt-14505.html
Page 'https://gameforge.com/' doesn't have enough links
Validating https://www.berliner-volksbank.de/privatkunden/beratung-service/beratungsangebot.html
Validating https://conceptsauce.com/pack-testing-evaluate-your-packaging-design/
Validating https://www.ran.de/sports/fussball/klub-wm/news/fifa-klub-wm-fc-bayern-vs-paris-saint-germain-pechvogel-kane-drama-um-musiala-noten-zum-viertelfinale-557191
Validating https://www.rs2.de
Page 'http://owa.student.kuleuven.be' doesn't have enough links
Validating https://www.dasoertliche.de/postleitzahlen/
Validating https://sportbild.bild.de/sportmix/fighting/boxen/home-33310312.sport.html
Validating https://www.paypal.com/us/cshelp/personal
Finished generating URL map for http://glosbe.com
Validating https://doodle.com/en/product/sign-up-sheet/
Validating https://www.essen-und-trinken.de/rezepte/schneller-zucchini-salat-mit-feta-und-mandeln-14011414.html
Validating https://www.gutefrage.net/highlights/tsoul-vs-adel-tawil
Validating https://www.instagram.com/rs2.berlin/
Validating https://www.dpd.com/de/de/logistikpartner-im-fernverkehr/
Validating https://de.pornhub.com/view_video.php?viewkey=6841a03e153b1
Validating https://toledo.kuleuven.be
Validating https://kdp.amazon.com/publish
Finished generating URL map for https://www.leben-und-erziehen.de/eltern-empfehlen?utm_source=redirect_service&utm_medium=redirect&utm_campaign=redirect_service
Validating https://peggo.online/youtube-downloader
Validating https://www.ran.de/service/barrierefreiheit
Validating https://mpmath.org/doc/current/
Validating https://service.berlin.de/barrierefreiheitserklaerung.995187.php
Validating https://www.berlin.de/einwanderung/
Validating https://www.amazon.de/Denken-Rechnen-Allgemeine-Ausgabe-Arbeitsheft/dp/3141264244/?_encoding=UTF8&pd_rd_w=T35CT&content-id=amzn1.sym.cd74953f-b529-416f-aef4-f3454e124e78&pf_rd_p=cd74953f-b529-416f-aef4-f3454e124e78&pf_rd_r=KJG4PMF8FC4SJHE6EBBX&pd_rd_wg=C37Bf&pd_rd_r=72a56450-f9b7-4af8-b4b5-ff1a35909fe9&ref_=pd_hp_d_btf_crs_zg_bs_186606
Validating https://www.dhl.de/de/privatkunden/hilfe-kundenservice/sendungsverfolgung/probleme-loesungen.html
Validating https://savanta.com/research-consulting/stakeholders/employee
Validating https://www.lvz.de/sport/besondere-unterstutzung-fur-dfb-verteidigerin-franziska-kett-9befae93-0b61-493d-918e-a7d04ec83772.html
Validating https://conceptsauce.com/range-builder/
Validating https://store.google.com/US?utm_source=hp_header&utm_medium=google_ooo&utm_campaign=GS100042&hl=en-US
Validating https://www.ardmediathek.de/mdr
Validating https://service.deutschlandsim.de#sendPasswordNotification-tab
Page 'https://de-play.forgeofempires.com' doesn't have enough links
Validating https://overview.mail.yahoo.com/
Validating https://tr.wikipedia.org/wiki/
Validating https://www.gutefrage.net/business/
Validating https://web.de/magazine/ratgeber/essen-trinken/
Validating https://sportbild.bild.de/fussball/internationaler-fussball/fc-barcelona-schnappt-sich-chelsea-diesen-flick-liebling-68676b9406de2411019a66aa
Validating https://www.gmx.net/vergleichswelt/bildung/bachelor/?mc=85500011
Validating https://doodle.com/en/solutions/recruiting/
Validating https://peggo.online/youtube-downloader
Validating https://de.search.yahoo.com/preferences/preferences;_ylt=AwrjfYbUDWpohowj44IyCQx.?pref_done=https%3A%2F%2Fde.search.yahoo.com%2F%3Fei%3DUTF-8&.bcrumb=
Validating https://www.berliner-volksbank.de/agb-und-sonderbedingungen.html
Validating https://www.heise.de/news/Von-Minimalismus-bis-zu-farbenpraechtigen-Landschaften-Die-Bilder-der-Woche-27-10468040.html
Page 'https://onlinebewerbung.eventit.ag/' doesn't have enough links
Validating https://www.betternet.co/windows-vpn/
Validating http://lagrp.justiz.rlp.de/themen/elektronischer-rechtsverkehr
Finished generating URL map for https://toledo.kuleuven.be/
Validating https://www.dasoertliche.de/Personensuche/Nachnamen-I
Error validating http://www.amazon.com/gp/help/customer/display.html/ref=footer_cou?ie=UTF8&nodeId=508088: 403, message='Forbidden', url='https://www.amazon.com/gp/help/customer/display.html/ref=footer_cou?ie=UTF8&nodeId=508088'
Validating https://www.amazon.com/gp/help/customer/account-issues/ref=ap_login_with_otp_claim_collection?ie=UTF8
Validating https://www.deezer.com/us/offers
Validating https://service.berlin.de/wirtschaft/
Validating https://www.dpd.com/de/de/empfangen/dpd-app/

CancelledError: